#!/usr/bin/env python

import sys
from urllib import urlopen, urlencode

def paste(code="", lang="Python"):
    data = {"code": code, "lang": lang, "submit": "Submit"}
    url = "http://codepad.org/"
    r = urlopen(url, urlencode(data))
    if r.code == 200:
        return r.url
    else:
        return r

print paste(sys.stdin.read())
