#!/usr/bin/env python

import re
import time

import proxmox

# connect to one of the proxmox nodes and get authenticated
c = proxmox.Connector("vz1")
c.get_auth_token("root@pam", "ebAXD17XW2h8")

# connect to the node you wish to perform actions on.
node = proxmox.Node(c, "vz1")
