#!/usr/bin/env python

"""rmbom

Command-line tool to remove BOM markers from
files.

Usage: rmbom [options] file
"""

import sys
import optparse
from cStringIO import StringIO

__version__ = "0.1"

USAGE = "%prog [options] file"
VERSION = "%prog v" + __version__

def parse_options():
	"""parse_options() -> opts, args

	Parse any command-line options given returning both
	the parsed options and arguments.
	"""

	parser = optparse.OptionParser(usage=USAGE, version=VERSION)

	opts, args = parser.parse_args()

	if len(args) < 1:
		parser.print_help()
		raise SystemExit, 1

	return opts, args

def rmbom(file):
	r = open(file, "rU")
	w = StringIO()
	line = r.next()
	line = line.rstrip()
	if line[:3] == "\xef\xbb\xbf":
		line = line[3:]
	w.write("%s\n" % line)
	for line in r:
		line = line.rstrip()
		w.write("%s\n" % line)
	r.close()
	w.flush()
	s = w.getvalue()
	w.close()

	w = open(file, "w")
	w.write(s)
	w.close()

def main():
	opts, args = parse_options()

	rmbom(args[0])

if __name__ == "__main__":
	main()
