#!/Users/s2092651/bin/python
# EASY-INSTALL-DEV-SCRIPT: 'ccav==0.0.4.dev2','tileindex'
__requires__ = 'ccav==0.0.4.dev2'
from pkg_resources import require; require('ccav==0.0.4.dev2')
del require
__file__ = '/Users/s2092651/work/ccaih/ccav/scripts/tileindex'
execfile(__file__)
